version: '3'

services:
  wicket:
    build: .
    container_name: wicket
    env_file: .env
    # environment:
      # DISCORD_ADMINS: MyUser#1234,MyOtherUser#4321
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
